// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OffRosterAPI.Models;

namespace OffRosterAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200221201645_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OffRosterAPI.Models.OffRosterRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActioned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOpenEnded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OffRosterCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RequestingManager")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ThreeLetterCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("OffRosterRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
